# Splits file generation (K-Means)

The notebook for generating and assigning the clusters (`k_means_clustering_splits_generation.ipynb`) is [here](https://github.com/akshatzalte/chemprop/blob/rigr_home/notebooks/k_means_clustering_splits_generation.ipynb). In this notebook, the cluster assignments are simply used to create the `splits.json` files for unaugmented and augmented cases.

In [1]:
import pandas as pd
import json
import random

In [2]:
all_data_set = pd.read_csv("dataset/all_data_set.csv")
all_aug_data_set = pd.read_csv("dataset/all_aug_data_set.csv")

In [3]:
all_data_set.columns

Index(['parent_smi', 'resonance_smis', 'num_resonance_structures',
       'multiplicity', 'H298', 'H298_kcal', 'subset', 'rdkit_mol',
       'num_heavy_atoms', 'mol_wt', 'num_rings', 'num_rotatable_bonds',
       'num_aromatic_rings', 'mol_graph_diameter', 'weights', 'cluster_id'],
      dtype='object')

In [4]:
test_val_clusters = \
[([2, 16], [7, 12]),
 ([2, 16], [6]),
 ([2, 16], [1, 3]),
 ([2, 16], [17, 12]),
 ([2, 16], [4, 8])
  ]

In [ ]:
all_ids = list(range(18))

splits = []

aug_splits = []


for i, (test, val) in enumerate(test_val_clusters):
    test_val = test+val
    print(test_val)
    train = list(set(all_ids) - set(test_val))
    print(train)
    test_indices = all_data_set.index[all_data_set['cluster_id'].isin(test)].tolist()
    train_indices = all_data_set.index[all_data_set['cluster_id'].isin(train)].tolist()
    val_indices = all_data_set.index[all_data_set['cluster_id'].isin(val)].tolist()
    
    new_split = {
        "test": test_indices,
        "train": train_indices,
        "val": val_indices
    }
    
    # Add the new split to the list
    splits.append(new_split)
    
    selected_test = all_data_set.loc[test_indices].parent_smi.tolist()
    selected_train = all_data_set.loc[train_indices].parent_smi.tolist()
    selected_val = all_data_set.loc[val_indices].parent_smi.tolist()

    aug_test_indices = list(all_aug_data_set[all_aug_data_set["parent_smi"].isin(selected_test)].index)
    aug_train_indices = list(all_aug_data_set[all_aug_data_set["parent_smi"].isin(selected_train)].index)
    aug_val_indices = list(all_aug_data_set[all_aug_data_set["parent_smi"].isin(selected_val)].index)

    new_aug_split = {
            "test": aug_test_indices,
            "train": aug_train_indices,
            "val": aug_val_indices
        }
    aug_splits.append(new_aug_split)

# Save to splits.json
# with open('dataset/splits.json', 'w') as file:
#     json.dump(splits, file, indent=4)

# with open('dataset/aug_splits.json', 'w') as file:
#     json.dump(aug_splits, file, indent=4)

[2, 16, 7, 12]
[0, 1, 3, 4, 5, 6, 8, 9, 10, 11, 13, 14, 15, 17]
[2, 16, 6]
[0, 1, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17]
[2, 16, 1, 3]
[0, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17]
[2, 16, 17, 12]
[0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15]
[2, 16, 4, 8]
[0, 1, 3, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 17]

In [6]:
all_data_set.columns

Index(['parent_smi', 'resonance_smis', 'num_resonance_structures',
       'multiplicity', 'H298', 'H298_kcal', 'subset', 'rdkit_mol',
       'num_heavy_atoms', 'mol_wt', 'num_rings', 'num_rotatable_bonds',
       'num_aromatic_rings', 'mol_graph_diameter', 'weights', 'cluster_id'],
      dtype='object')

In [7]:
import pandas as pd
final_test = pd.read_csv("dataset/final_test.csv")

In [8]:

all_test = pd.merge(final_test, all_data_set[['resonance_smis', 'cluster_id', 'subset', 'num_resonance_structures']], on='resonance_smis', how='left')

In [9]:
import pandas as pd

# Example DataFrame

# Count occurrences of each subset
subset_counts = all_test['subset'].value_counts()

# Create a table
print(subset_counts)

subset
res_radical         2054
res_closed_shell    1802
non_resonance        938
Name: count, dtype: int64

In [25]:
summary_statistics = all_test.groupby('subset')['num_resonance_structures'].describe()

In [26]:
summary_statistics

                   count      mean       std  min  25%  50%  75%   max
subset
non_resonance     1259.0  1.000000  0.000000  1.0  1.0  1.0  1.0   1.0
res_closed_shell  1586.0  2.228247  0.531277  2.0  2.0  2.0  2.0   6.0
res_radical       2435.0  2.824641  1.366659  2.0  2.0  2.0  3.0  13.0

In [22]:
all_data_set.groupby('subset')['num_resonance_structures'].describe()

                    count     mean       std  min  25%  50%  75%   max
subset
non_resonance     10000.0  1.00000  0.000000  1.0  1.0  1.0  1.0   1.0
res_closed_shell  20000.0  2.33615  0.679468  2.0  2.0  2.0  2.0   8.0
res_radical       20000.0  3.25615  1.991892  2.0  2.0  2.0  4.0  29.0